"""
Auto-Doc Updater — Keeps CLAUDE.md always current
===================================================
Scans the entire codebase and regenerates CLAUDE.md automatically.

Run after every session:
    python update_docs.py

Or add to your end-of-day routine:
    python update_docs.py && git add CLAUDE.md && git commit -m "docs: auto-update"
"""

from __future__ import annotations

import ast
import subprocess
from datetime import datetime
from pathlib import Path

BASE_DIR = Path(__file__).parent

# ── Helpers ───────────────────────────────────────────────────────────────────

def _git_log(n: int = 5) -> list[str]:
    try:
        out = subprocess.check_output(
            ["git", "log", f"-{n}", "--oneline"], cwd=BASE_DIR, text=True
        )
        return out.strip().splitlines()
    except Exception:
        return []


def _docstring(path: Path) -> str:
    """Extract first line of module docstring."""
    try:
        tree = ast.parse(path.read_text(errors="replace"))
        doc  = ast.get_docstring(tree)
        if doc:
            return doc.splitlines()[0].strip()
    except Exception:
        pass
    return ""


def _count_lines(path: Path) -> int:
    try:
        return len(path.read_text(errors="replace").splitlines())
    except Exception:
        return 0


def _file_table(files: list[Path], base: Path) -> str:
    rows = ["| File | Purpose | Lines |", "|------|---------|-------|"]
    for f in sorted(files):
        rel   = f.relative_to(base)
        doc   = _docstring(f) or "—"
        lines = _count_lines(f)
        rows.append(f"| `{rel}` | {doc} | {lines} |")
    return "\n".join(rows)


def _page_table(pages: list[Path]) -> str:
    rows = ["| Page | Route | Description |", "|------|-------|-------------|"]
    for p in sorted(pages):
        name  = p.stem
        route = "/" + name.split("_", 1)[-1].replace("_", " ") if "_" in name else name
        doc   = _docstring(p) or "—"
        rows.append(f"| `{name}` | `{route}` | {doc} |")
    return "\n".join(rows)


def _db_tables() -> str:
    import sqlite3
    db = BASE_DIR / "dashboard.sqlite"
    if not db.exists():
        return "_database.sqlite not found — run the app first_"
    try:
        conn   = sqlite3.connect(str(db))
        tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
        conn.close()
        rows   = ["| Table | Description |", "|-------|-------------|"]
        desc_map = {
            "engine_orders":   "All orders (paper + live) with fill info",
            "strategy_trades": "Strategy signal log with P&L",
            "sl_positions":    "Active stop-loss positions",
            "trade_journal":   "Manual trade diary entries",
        }
        for (t,) in tables:
            rows.append(f"| `{t}` | {desc_map.get(t, '—')} |")
        return "\n".join(rows)
    except Exception:
        return "_Could not read DB tables_"


# ── Main builder ──────────────────────────────────────────────────────────────

def build_claude_md() -> str:
    now        = datetime.now().strftime("%Y-%m-%d %H:%M")
    pages      = sorted(BASE_DIR.glob("pages/*.py"))
    pages      = [p for p in pages if not p.name.startswith("__")]
    core_files = [
        BASE_DIR / f for f in [
            "app.py", "kite_data.py", "config.py", "auth_streamlit.py",
            "generate_token.py", "alert_engine.py", "logger.py",
        ] if (BASE_DIR / f).exists()
    ]
    live_files = [
        BASE_DIR / f for f in [
            "ticker_service.py", "market_data.py",
        ] if (BASE_DIR / f).exists()
    ]
    strategy_files = sorted((BASE_DIR / "strategies").glob("*.py")) if (BASE_DIR / "strategies").exists() else []
    strategy_files = [f for f in strategy_files if not f.name.startswith("__")]

    engine_files = [
        BASE_DIR / f for f in [
            "strategy_engine.py", "signal_engine.py", "indicators.py",
            "fo_symbols.py", "regime_filter.py",
        ] if (BASE_DIR / f).exists()
    ]
    exec_files = [
        BASE_DIR / f for f in [
            "order_manager.py", "stop_loss_manager.py",
            "risk_manager.py", "position_sizer.py",
        ] if (BASE_DIR / f).exists()
    ]
    infra_files = [
        BASE_DIR / f for f in [
            "process_guard.py", "scheduler.py",
            "auto_renew_token.py", "db.py",
        ] if (BASE_DIR / f).exists()
    ]
    backtest_files = [
        BASE_DIR / f for f in [
            "backtest_engine.py", "backtest_runner.py",
        ] if (BASE_DIR / f).exists()
    ]

    recent_commits = "\n".join(f"- {c}" for c in _git_log(5)) or "_No git history_"

    doc = f"""# Algo Trading System — Project Map
> Auto-generated by `update_docs.py` on **{now}**
> Run `python update_docs.py` after every session to keep this current.

---

## What this project is
A production-grade algorithmic trading system built on Zerodha Kite API + Streamlit dashboard.
**Owner:** Ricky | **Broker:** Zerodha | **Exchange:** NSE / NFO (F&O)

---

## How to start every session
```bash
cd backtest-main
source venv/bin/activate
python generate_token.py <request_token>   # Step 1 — once per morning
python ticker_service.py                   # Step 2 — live WebSocket prices
streamlit run app.py                       # Step 3 — dashboard
# OR start everything at once:
python process_guard.py                    # keeps all services alive
```

---

## Environment (.env)
| Key | Description |
|-----|-------------|
| `API_KEY` | Kite API key (also `KITE_API_KEY`) |
| `API_SECRET` | Kite API secret (also `KITE_API_SECRET`) |
| `TELEGRAM_TOKEN` | Telegram bot token (also `TELEGRAM_BOT_TOKEN`) |
| `TELEGRAM_CHAT_ID` | Your Telegram chat ID |
| `ANTHROPIC_API_KEY` | Claude API key (for chatbot page) |

**All keys unified via `config.py` — always import `cfg` from there.**

---

## Dashboard Pages ({len(pages)} pages)

{_page_table(pages)}

---

## File Map

### Core
{_file_table(core_files, BASE_DIR)}

### Live Data
{_file_table(live_files, BASE_DIR)}

### Signal & Intelligence Layer
{_file_table(engine_files, BASE_DIR)}

### Strategy Layer
{_file_table(strategy_files, BASE_DIR) if strategy_files else "_See strategies/ folder_"}

### Execution Layer
{_file_table(exec_files, BASE_DIR)}

### Backtesting
{_file_table(backtest_files, BASE_DIR)}

### Infrastructure
{_file_table(infra_files, BASE_DIR)}

---

## Database (`dashboard.sqlite`)
{_db_tables()}

---

## Signal Scoring System
- **10 indicators:** RSI, MACD, Bollinger Bands, Supertrend, EMA Crossover, VWAP, Volume Spike, ADX, Stochastic, OI Change
- **Score range:** -15 to +15
- **BUY threshold:** ≥ +6 | **SELL threshold:** ≤ -6
- **Universe:** 6 F&O indices + ~180 F&O stocks (`fo_symbols.py`)

---

## Adding a new strategy
1. Create `strategies/my_strategy.py` inheriting `BaseStrategy`
2. Implement `name`, `description`, `on_tick()` → return `Signal` or `None`
3. Add to `strategies/__init__.py`
4. Add to `ACTIVE_STRATEGIES` in `strategy_engine.py`
5. Add to `STRATEGY_MAP` in `pages/16_Backtest.py`

## Adding a new indicator
1. Add function `check_xxx()` to `indicators.py` returning +weight / -weight / 0
2. Call it inside `score_symbol()` and add to `_add()` calls
3. Update `MAX_SCORE` at top of file

---

## Key architectural decisions
- **Terminal-only auth:** run `python generate_token.py` once every morning
- **WebSocket ticks:** `ticker_service.py` writes `ticker_data.json` every tick
- **Confluence scoring:** 10-indicator weighted system — trade only on agreement
- **PAPER / LIVE modes:** toggle per strategy in hub or signal scanner
- **Central logger:** all files use `from logger import get_logger`
- **Central DB:** all files use `from db import execute, query, read_df`
- **Single symbol registry:** always import symbols from `fo_symbols.py`

---

## Recent git commits
{recent_commits}

---

## Stats (auto-counted)
- Dashboard pages: **{len(pages)}**
- Core Python files: **{len(list(BASE_DIR.glob("*.py")))}**
- Strategy files: **{len(strategy_files)}**
"""
    return doc


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("🔄 Scanning codebase...")
    content = build_claude_md()
    out = BASE_DIR / "CLAUDE.md"
    out.write_text(content, encoding="utf-8")
    print(f"✅ CLAUDE.md updated ({len(content.splitlines())} lines)")
    print(f"   → {out}")
